#ifndef _COORDINATESANDOFFSETS_H
#define _COORDINATESANDOFFSETS_H

// Coordinates
#define HOME_POSITION_X 100
#define HOME_POSITION_Y 137

#define TRIANGLE_SORTED_X 243
#define TRIANGLE_SORTED_Y 137

#define SQUARE_SORTED_X 317
#define SQUARE_SORTED_Y 137

#define RECTANGLE_SORTED_X 100
#define RECTANGLE_SORTED_Y 137

#define CIRCLE_SORTED_X 173
#define CIRCLE_SORTED_Y 137

// Offsets
#define AXIS_X_LOWER 85
#define AXIS_X_HIGHER 375
#define AXIS_Y_LOWER 58
#define AXIS_Y_HIGHER 424

#define TOOL_OFFSET_X 10018
#define TOOL_OFFSET_Y 11577

#endif // _COORDINATESANDOFFSETS_H 
